### ISSUE TITLE
Reason for noscript inside picture?

### ISSUE THREAD

**Issue by nextgenthemes** [mfranzke/loading-attribute-polyfill#11]
Just curious if and what the reason for this:

```html
<picture>
	<noscript class="loading-lazy">
		<source
			media="(min-width: 40em)"
			srcset="
				simpleimage.huge.jpg 1x,
				simpleimage.huge.2x.jpg 2x
			"
		/>
		<source
			srcset="
				simpleimage.jpg 1x,
				simpleimage.2x.jpg 2x
			"
		/>
		<img
			src="simpleimage.jpg"
			loading="lazy"
			alt=".."
			width="250"
			height="150"
		/>
	</noscript>
</picture>
```
Instead of 

```html
<noscript class="loading-lazy">
<picture>
		<source
			media="(min-width: 40em)"
			srcset="
				simpleimage.huge.jpg 1x,
				simpleimage.huge.2x.jpg 2x
			"
		/>
		<source
			srcset="
				simpleimage.jpg 1x,
				simpleimage.2x.jpg 2x
			"
		/>
		<img
			src="simpleimage.jpg"
			loading="lazy"
			alt=".."
			width="250"
			height="150"
		/>
</picture>
</noscript>
```

Now that I think of it probably because of styling the `<picture>` already has

**Comment by mfranzke** [comment]
Good question.

I would have loved to keep it „consistent“ with the simplest one (<img /> only) where only that tag itself (<img />) is being wrapped to prevent the loading of the image in the first place. Sadly some browsers but not all are still loading the images referenced out of the <source /> tags.

This even also leads to the aspect that you mentioned to still have the <picture> tag outside available to reference for e.g. styling or scripting - it‘s probably not the most important aspect, but there aren‘t most likely any more arguments for both ways (wrapping inside or outside), so this might be the „best“.
