### ISSUE TITLE
Submit to cdnjs

### ISSUE THREAD

**Issue by curbengh** [mfranzke/loading-attribute-polyfill#15]
Unlike jsDelivr, [cdnjs](https://github.com/cdnjs/cdnjs)'s entry needs to be manually added. I don't mind submitting a PR there, but I think it would be best for the author to do it (more _official_ sort of).

They do give priority to popular (many :star:) library (>100 PRs still open), but judging by the usefulness and easy-to-integrate of this library, I figure why not give it a try.

**Comment by mfranzke** [comment]
@curbengh, great reminder, thanks a lot ! I even also did this for my first polyfill and it worked quite nicely, so I‘ll proceed like this directly.

**Comment by mfranzke** [comment]
added a PR to cdnjs: https://github.com/cdnjs/cdnjs/pull/13440

**Comment by mfranzke** [comment]
sadly they've declined the request, but it wouldn't take us too long to reach that 200 stars goal, would it?

**Comment by curbengh** [comment]
I'm sure this library can reach that easily as more webdev get to know about native lazy loading.

**Comment by mfranzke** [comment]
Currently this library is constantly increasing on its NPM downloads, so I could most likely submit a new request soon.

**Comment by mfranzke** [comment]
we're near that 800 goal even already, let's see what tomorrow brings: http://npm-stats.org/#/loading-attribute-polyfill

**Comment by mfranzke** [comment]
added a PR to cdnjs: cdnjs/cdnjs#13521 / issue: cdnjs/cdnjs#13520

**Comment by mfranzke** [comment]
Because of a bug the polyfill hasn't been added so far: https://github.com/cdnjs/cdnjs/issues/13668 - but I'm working on it !

**Comment by mfranzke** [comment]
It‘s available now: https://cdnjs.com/libraries/loading-attribute-polyfill
