### ISSUE TITLE
Can you load this script asynchronously?

### ISSUE THREAD

**Issue by Flimm** [mfranzke/loading-attribute-polyfill#2]
Will the script work correctly if loaded asynchronously, like this?

    <script src="loading-attribute-polyfill.js" async></script>

If so, it would be useful if README.md documented that.

**Comment by mfranzke** [comment]
yes, it does - compare to e.g. https://jsbin.com/yitarajawe/edit?html,css

I'll mention it within the spec.

**Comment by Flimm** [comment]
Thank you!

**Comment by mfranzke** [comment]
De nada
