### ISSUE TITLE
Chrome 77 lazyload doesn't work

### ISSUE THREAD

**Issue by OgNellis** [mfranzke/loading-attribute-polyfill#36]
Version 76 and lower work fine.
Chrome 77 load all images at once.
It is checked for a demo https://mfranzke.github.io/loading-attribute-polyfill/demo/

**Comment by mfranzke** [comment]
@OgNellis, thanks for reporting this. Have you checked whether this is related to the code that this polyfill provides? (I'm currently on a very slow connection and can't fulfill this at the moment).
