### ISSUE TITLE
Wrap in <iframe> or <noscript>?

### ISSUE THREAD

**Issue by diogoterremoto** [mfranzke/loading-attribute-polyfill#4]
Hello, and thank you for making this polyfill.

The `README.md` says that elements must be wrapped by `<iframe>`, but the examples are being wrapped with `<noscript>`. Am I understanding wrong? Which is it?

Thanks again.

**Comment by dracos** [comment]
I'd just noticed this too, and have made https://github.com/mfranzke/loading-attribute-polyfill/pull/5 as reading the code I'm pretty sure it is the word that is incorrect, not the examples.

**Comment by diogoterremoto** [comment]
Cool, you were less lazy that me :–)
Thank you for that PR.

**Comment by mfranzke** [comment]
totally agreed, thanks a lot for your support !!!
