### ISSUE TITLE
No images load in browsers that don't support media queries

### ISSUE THREAD

**Issue by cbirdsong** [mfranzke/loading-attribute-polyfill#41]
Found an error when doing some testing in IE9 - no images at all. From the look of things, it's because it doesn't support media queries, or specifically matchMedia:

```
SCRIPT438: Object doesn't support property or method 'matchMedia' 
loading-attribute-polyfill.min.js?ver=1.1.0, line 5 character 1942
```

I wouldn't expect a first-class lazyloading experience in such an old browser, but ideally images would err on the side of loading inefficiently instead of failing, just like older browsers without IntersectionObserver.

**Comment by cbirdsong** [comment]
Thanks!

**Comment by mfranzke** [comment]
Sure, thank you for this finding. Have you positively retested this?

**Comment by cbirdsong** [comment]
I haven’t – will check it out on Monday.

**Comment by mfranzke** [comment]
Okay, no hassle. I‘ll even also make a npm release soon, so than it could get retested this way as well.

I did test it on a local Virtual Machine.
