### ISSUE TITLE
README needs wording better to avoid confusion

### ISSUE THREAD

**Issue by TomS-** [mfranzke/loading-attribute-polyfill#46]
So I've used countless polyfills etc. I can't seem to get this one working? 

I have the script included using WebPack, I've checked the main.js and the script is in there, however, the images with `loading="lazy"` are not lazyloading, this is on Firefox. The strange thing is the demo works fine. I've tried including the script on it's own in the head and no difference. 

Here is my dev site you can see the problem: https://www.peterandpauldev.co.uk/ppfinal/work/ if  you inspect element, there is image that should be off screen, it loads straight away. I've tried to debug it but I really don't know how to test if this script is working or not, no errors are being returned.

**Comment by TomS-** [comment]
Nevermind, there was some confusion my end regarding the docs: 
`Just integrate the JavaScript file into your code - et voilà.` 
I thought it was as simple as that...

`You could even load the polyfill asynchronously: https://output.jsbin.com/codelib/1

Afterwards you'll need to wrap all of your <img> and <iframe> HTML tags that you'd like to lazy load (and thatfor added a loading="lazy" attribute as well) by an <noscript> HTML tag:`

I thought this was if you load asynchronously, but it needs applying regardless. The `Just integrate the JavaScript file into your code - et voilà.`  is a little misleading.

**Comment by mfranzke** [comment]
@TomS- totally agreed on that. I'll change it directly.
