### ISSUE TITLE
Include the script with webpack

### ISSUE THREAD

**Issue by white-gecko** [mfranzke/loading-attribute-polyfill#64]
> First you'll need to integrate the JavaScript file into your code.

I installed the script with `npm install loading-attribute-polyfill`, import it in my `index.js` with `import 'loading-attribute-polyfill';` and ran `npm webpack`. (As you see I'm using webpack.)

I checked and it is in the `main.js` that is loaded by my browser but unfortunately the images remain blank.

What else do I have to do to load the polyfill?

**Comment by mfranzke** [comment]
Any chance for hosting your code online, e.g. from your own environment or via jsfiddle ?

**Comment by white-gecko** [comment]
Yes, I've wrapped all of the img tags in a noscript tag and added the loading="lazy" to the img tags.
I've just pushed these changes to my webpage: https://natanael.arndt.xyz/

**Comment by mfranzke** [comment]
For whatevery reason the script that you're generating on your website works perfectly fine when included within the demo page https://mfranzke.github.io/loading-attribute-polyfill/demo/ as a replacement of the script out of the repo itself.
In exchange, when including the script out of this repo directly into your page, it doesn't work either. So I would need to further investigate, but don't expect a problem with your Webpack for the moment.

**Comment by mfranzke** [comment]
@white-gecko, I've found the problem - it doesn't relate to Webpack, but to the code that you're using on your implementation: you're wrapping the `<img />` HTML Tag within the `<noscript>` HTML tag with an additional `<p>` HTML tag, which causes this problem, compare those two simplified examples, just including the image and the JS referenced by your server:
- [Your code](http://jsfiddle.net/kjshjhrkshdjhsfkhsgdfj/npem6txh/embedded/result/)
- [Your code with the `<p>` tag removed](http://jsfiddle.net/kjshjhrkshdjhsfkhsgdfj/g4w0ne3a/embedded/result/)

**Comment by white-gecko** [comment]
Ah ok, this was due to the markdown/kamdown used by jekyll. It introduced a paragraph inside the include which was strange for me. Now I could disable the extra markdown interpretation (using markdown="0" in the enclosing tag). Lacy loading makes my webpage now much more carbon (https://www.websitecarbon.com/website/natanael-arndt-xyz/) friendly, thank you.

**Comment by mfranzke** [comment]
@white-gecko, you‘re welcome. Dafür nicht! ;-)

**Comment by TomDeSmet** [comment]
Sorry I open up this closed thread again, but I'm having the same problem. I imported the script in my app.js file, it's being compiled by Webpack and my images are loaded as such:

```
<picture class="w-full">
    <noscript class="loading-lazy">
        <source srcset="{{- uniqueSrcset | join(', ') -}}" sizes="{{- sizes | join(', ') -}}" />
        <img loading="lazy" class="w-full" src="{{ image.getUrl(transform|merge({width: fallbackWidth})) }}" alt="{{(image.title is defined) ? image.title : ''}}" style="object-position: {{ cropPosition }}" >
    </noscript>
</picture>
```

Which outputs this for example:

```
<picture class="w-full">
    <source data-lazy-srcset="data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%270 0 1 1%27%3E%3C/svg%3E" data-lazy-remove="true">
    <source data-lazy-srcset="http://mywebsite.com/path/to/asset/_767xAUTO_fit_center-center_80_none/temp.jpg 767w, http://mywebsite.com/path/to/asset/_1534xAUTO_fit_center-center_80_none/temp.jpg 1534w, http://mywebsite.com/path/to/asset/_1023xAUTO_fit_center-center_80_none/temp.jpg 1023w, http://mywebsite.com/path/to/asset/_1840x1200_fit_center-center_80_none/temp.jpg 2046w, http://mywebsite.com/path/to/asset/_1050xAUTO_fit_center-center_80_none/temp.jpg 1050w, http://mywebsite.com/path/to/asset/_1840x1200_fit_center-center_80_none/temp.jpg 2099w" sizes="(max-width: 767px) 100vw, (max-width: 1023px) 100vw, (max-width: 1399px) 75vw, 1049.25px"> <img loading="lazy" src="data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%270 0 1 1%27%3E%3C/svg%3E" data-lazy-src="http://mywebsite.com/path/to/asset/_1400xAUTO_fit_center-center_80_none/temp.jpg" alt="Temp" class="w-full" style="object-position: 50%;"></picture>
```

In Chrome it works, but Firefox and Safari show blanks and nothing gets loaded.

**Comment by mfranzke** [comment]
@TomDeSmet , easy. Do you have a publicly accessible URL for analyzing the problem ?

**Comment by TomDeSmet** [comment]
Not publicly available. But I could send you the link and password to the frontend in private?
How can I contact you? By mail, Discord, ...?

**Comment by mfranzke** [comment]
by mail. I've just send you a message to your gmail account.
