### ISSUE TITLE
Does it make sense to setup lazy loading for images above the fold?

### ISSUE THREAD

**Issue by rfgamaral** [mfranzke/loading-attribute-polyfill#89]
If I have a couple of images **above the fold** does it make sense to lazy load those images? Based on my research, the browser will load any images as soon as any `<img>` tags are parsed above the fold, effectively skipping the native lazy loading mechanism.

Assuming this polyfill implements the native lazy loading mechanism as close as possible to the spec, there's also no gain whatsoever in setting up this polyfill to load images above the fold.

Am I right in both those assumptions? Please advise and correct me if I'm wrong.

**Comment by mfranzke** [comment]
@rfgamaral, thanks a lot for your question.

In general I would say, it depends. The main reason for this is that it's sometimes hard to determine "above the fold". From my understanding of the specs and further discussions on the topic there wouldn't be a benefit for any items that are clearly and at all even small viewports being displayed right away.

But think about even the difference of portrait vs. landscape mode for small smartphone devices and the resulting small height of the viewport. In other words, a small logo that always sits in the header is probably a good candidate to not use the `loading`-attribute for as well as the hero image which is displayed directly as the first item within the content section. But any further image might be under someones fold and that for retrieve a benefit from setting this attribute.
