### ISSUE TITLE
https://validator.w3.org/ reports errors

### ISSUE THREAD

**Issue by denyshutsal** [mfranzke/loading-attribute-polyfill#90]
https://validator.w3.org/ reports errors

![Снимок](https://user-images.githubusercontent.com/15982606/86886579-dae73380-c0ff-11ea-8574-788b45a781ad.PNG)

**Comment by mfranzke** [comment]
great catch, thanks a lot, @denyshutsal ! This could be a late answer and clearly point the decision/answer out of #11 in the other direction, and might lead to a breaking change within the HTML code with one of the next releases to have this fixed.

**Comment by denyshutsal** [comment]
Many thanks
