### ISSUE TITLE
Not working on Safari 13.0.5 

### ISSUE THREAD

**Issue by Alfrex92** [mfranzke/loading-attribute-polyfill#93]
Hi, I imported this script 
`  <script async src="https://cdn.jsdelivr.net/npm/loading-attribute-polyfill@0.2.0/loading-attribute-polyfill.min.js" integrity="sha256-kX73NqVUoUbV0K44kgoqP8P8IZfU0OEjr/afCnK2Mrg=" crossorigin="anonymous"></script>
`
But, `lazy=loading" is still not working on Safari. Any idea how to fix it?

**Comment by mfranzke** [comment]
@Alfrex92 thanks for your feedback.

Could you please provise a jsbin or jsfiddle with your code?

**Comment by Alfrex92** [comment]
Thanks for your quick response 😄

Here it goes : https://codepen.io/alfrex92/pen/VwaaWEE

**Comment by mfranzke** [comment]
Ah, I see. You‘ve missed the step of wrapping the image with a <noscript class="loading-lazy"> HTML tag, than it should work fine.

**Comment by Alfrex92** [comment]
I added the `noscript` tag and it's not working 😢

**Comment by mfranzke** [comment]
> I added the `noscript` tag and it's not working 😢

I‘ll be back at my Mac tomorrow and will have a look.

**Comment by mfranzke** [comment]
Is there a reason why you're using one of the earliest releases, instead (one of) the newest, like e.g. https://cdn.jsdelivr.net/npm/loading-attribute-polyfill@1.5.4/loading-attribute-polyfill.min.js ?

**Comment by Alfrex92** [comment]
It seems working using `https://cdn.jsdelivr.net/npm/loading-attribute-polyfill@1.5.4/loading-attribute-polyfill.min.js` thanks 😃

> Is there a reason why you're using one of the earliest releases?

That's the only release that I was able to find. For future references where can I find the newest releases loaded from a CDN?

**Comment by mfranzke** [comment]
> It seems working using `https://cdn.jsdelivr.net/npm/loading-attribute-polyfill@1.5.4/loading-attribute-polyfill.min.js` thanks 😃
> 
> > Is there a reason why you're using one of the earliest releases?
> 
> That's the only release that I was able to find. For future references where can I find the newest releases loaded from a CDN?

Most of those services should be able to always deliver the latest software version when you leave out the version number within the URL, like e.g.: https://cdn.jsdelivr.net/npm/loading-attribute-polyfill/loading-attribute-polyfill.min.js

You could reach out to their documentation as there might be even further tweaks like e.g. specific minor versions etc.
