### ISSUE TITLE
SVG placeholder doesn't prevent reflow. Creates CLS problems.

### ISSUE THREAD

**Issue by bridgeport** [mfranzke/loading-attribute-polyfill#97]
First, thanks for your script. Your January 25, 2020 changelog states:
> Update placeholder to SVG to prevent reflow on lazyloaded images

However, this doesn't seem to prevent reflow as your script swaps out the src attribute after it loads and the page loads, which is too late.

It doesn't matter if your script is loaded in the head or before the closing body tag.

There has to be something that takes up the aspect ratio before your script kicks in. On page load, the noscript takes up no space and is collapsed. This causes the page to shift around later as images load.

This is why something like the intrinsic ratio padding box hack is still in use:
https://css-tricks.com/aspect-ratio-boxes/

Your script is susceptible to Cumulative Layout Shift (CLS), which will be a Core Web Vitals SEO ranking factor in May 2021, as explained here:
https://web.dev/optimize-cls/

Using an SVG placeholder seems to be a robust solution to jank, as detailed here:
https://css-tricks.com/preventing-content-reflow-from-lazy-loaded-images/

It would be great if your script could work using this technique. Or something similar.

Thanks.

**Comment by mfranzke** [comment]
@bridgeport thanks a lot for reporting this.
The changelog entry "Update placeholder to SVG to prevent reflow on lazyloaded images" was actually related to that we're using that SVG placeholder pattern in the script, introduced with https://github.com/mfranzke/loading-attribute-polyfill/pull/48

So I'd like to further understand your reporting, especially as you seem to be more involved in this performance topic already (I sadly missed the latest Google presentations on this). From by understand the following happens:

- Page load: Our script transforms the `noscript` HTML tags to img tags, either with the correct image URL in case that the feature detection for `loading=lazy` is true, or a SVG placeholder like you suggested.
- User scrolling towards the image: In case of a non-supporting `loading=lazy` browser, the SVG placeholder within the source gets replaced by the correct image URL.

Regarding that second aspect, the SVG placeholder reserves the exact same amount of space necessary in the dimensions that the real image would need to take later, both accounted for by the provided `width` and `height` attributes that should span that element to the intrinsic ratio size, as well as providing the SVG placeholder by that same width and height for the `viewBox`, as described in the article as well that you've provided.

So from my understanding, I could only think about that you're probably talking about that first step and the time before this script kicks in and replaces the `noscript` HTML tag by the `img` HTML tag, isn't it?
Again, as I said that I'm not that involved in already, I'd like to ask the following questions:
- Is there a difference on CLS regarding above and below the fold items? From my understanding CLS doesn't target below the fold items, as the user wouldn't recognize them anyhow. And as the attributes usage is mainly meant for below the fold items (I should then correct this in the demo as well), this is hopefully not that much of a problem.
- Have you actually measured the CLS, e.g. by Lighthouse >= 6.0 and on the demo page https://mfranzke.github.io/loading-attribute-polyfill/demo/? Or what might be the easiest setup for me to even also reproduce your findings?

**Comment by bridgeport** [comment]
@mfranzke You're correct. I was getting CLS scores above 0.1 (sometimes 0.4+), when lazyloading images above the fold. When I excluded such images (e.g., hero images, featured image), the CLS score dropped to zero. I'm loading your script async before the closing body tag.

On desktop, because I'm loading images in the sidebar, some CLS is still there for those images, but it's minor. About 0.02. On mobile, the sidebar is at the bottom of the viewport, so is unaffected. Not much I can do about that. I have to keep them marked as `loading="lazy"` or else mobile visitors will suffer. It's a worthwhile trade-off though.

Thanks for pointing this out.

**Comment by mfranzke** [comment]
@bridgeport the previous demo page was misleading about that - I deleted those images within the initial viewport and mention the general rules provided by the Google engineers as well as stating that on the README page.

I've additionally measured the CLS via Lighthouse and it's at zero now.

Sorry about the confusion that the previous demo pages content were leading to.

**Comment by bridgeport** [comment]
@mfranzke thanks again
